# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_gamesetting_conf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_gamesetting_conf.proto',
  package='',
  serialized_pb='\n\x1d\x63lient_gamesetting_conf.proto\"5\n\x17\x63lient_gamesetting_conf\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"H\n\x1d\x63lient_gamesetting_conf_array\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.client_gamesetting_confB\x02H\x03')




_CLIENT_GAMESETTING_CONF = _descriptor.Descriptor(
  name='client_gamesetting_conf',
  full_name='client_gamesetting_conf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='client_gamesetting_conf.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='client_gamesetting_conf.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=86,
)


_CLIENT_GAMESETTING_CONF_ARRAY = _descriptor.Descriptor(
  name='client_gamesetting_conf_array',
  full_name='client_gamesetting_conf_array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='client_gamesetting_conf_array.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=160,
)

_CLIENT_GAMESETTING_CONF_ARRAY.fields_by_name['items'].message_type = _CLIENT_GAMESETTING_CONF
DESCRIPTOR.message_types_by_name['client_gamesetting_conf'] = _CLIENT_GAMESETTING_CONF
DESCRIPTOR.message_types_by_name['client_gamesetting_conf_array'] = _CLIENT_GAMESETTING_CONF_ARRAY

class client_gamesetting_conf(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENT_GAMESETTING_CONF

  # @@protoc_insertion_point(class_scope:client_gamesetting_conf)

class client_gamesetting_conf_array(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENT_GAMESETTING_CONF_ARRAY

  # @@protoc_insertion_point(class_scope:client_gamesetting_conf_array)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
