-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"


FILE_ITEM = protobuf.Descriptor();
FILE_ITEM_URL_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_FILE_PATH_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_CREATED_TIME_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_SIZE_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_MD5_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_ARRAY = protobuf.Descriptor();
FILE_ITEM_ARRAY_ITEMS_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_ARRAY_URL_FIELD = protobuf.FieldDescriptor();
FILE_ITEM_ARRAY_VERSION_FIELD = protobuf.FieldDescriptor();

FILE_ITEM_URL_FIELD.name = "url"
FILE_ITEM_URL_FIELD.full_name = ".file_item.url"
FILE_ITEM_URL_FIELD.number = 1
FILE_ITEM_URL_FIELD.index = 0
FILE_ITEM_URL_FIELD.label = 1
FILE_ITEM_URL_FIELD.has_default_value = false
FILE_ITEM_URL_FIELD.default_value = ""
FILE_ITEM_URL_FIELD.type = 9
FILE_ITEM_URL_FIELD.cpp_type = 9

FILE_ITEM_FILE_PATH_FIELD.name = "file_path"
FILE_ITEM_FILE_PATH_FIELD.full_name = ".file_item.file_path"
FILE_ITEM_FILE_PATH_FIELD.number = 2
FILE_ITEM_FILE_PATH_FIELD.index = 1
FILE_ITEM_FILE_PATH_FIELD.label = 1
FILE_ITEM_FILE_PATH_FIELD.has_default_value = false
FILE_ITEM_FILE_PATH_FIELD.default_value = ""
FILE_ITEM_FILE_PATH_FIELD.type = 9
FILE_ITEM_FILE_PATH_FIELD.cpp_type = 9

FILE_ITEM_CREATED_TIME_FIELD.name = "created_time"
FILE_ITEM_CREATED_TIME_FIELD.full_name = ".file_item.created_time"
FILE_ITEM_CREATED_TIME_FIELD.number = 3
FILE_ITEM_CREATED_TIME_FIELD.index = 2
FILE_ITEM_CREATED_TIME_FIELD.label = 1
FILE_ITEM_CREATED_TIME_FIELD.has_default_value = false
FILE_ITEM_CREATED_TIME_FIELD.default_value = 0
FILE_ITEM_CREATED_TIME_FIELD.type = 13
FILE_ITEM_CREATED_TIME_FIELD.cpp_type = 3

FILE_ITEM_SIZE_FIELD.name = "size"
FILE_ITEM_SIZE_FIELD.full_name = ".file_item.size"
FILE_ITEM_SIZE_FIELD.number = 4
FILE_ITEM_SIZE_FIELD.index = 3
FILE_ITEM_SIZE_FIELD.label = 1
FILE_ITEM_SIZE_FIELD.has_default_value = false
FILE_ITEM_SIZE_FIELD.default_value = 0
FILE_ITEM_SIZE_FIELD.type = 13
FILE_ITEM_SIZE_FIELD.cpp_type = 3

FILE_ITEM_MD5_FIELD.name = "md5"
FILE_ITEM_MD5_FIELD.full_name = ".file_item.md5"
FILE_ITEM_MD5_FIELD.number = 5
FILE_ITEM_MD5_FIELD.index = 4
FILE_ITEM_MD5_FIELD.label = 1
FILE_ITEM_MD5_FIELD.has_default_value = false
FILE_ITEM_MD5_FIELD.default_value = ""
FILE_ITEM_MD5_FIELD.type = 9
FILE_ITEM_MD5_FIELD.cpp_type = 9

FILE_ITEM.name = "file_item"
FILE_ITEM.full_name = ".file_item"
FILE_ITEM.nested_types = {}
FILE_ITEM.enum_types = {}
FILE_ITEM.fields = {FILE_ITEM_URL_FIELD, FILE_ITEM_FILE_PATH_FIELD, FILE_ITEM_CREATED_TIME_FIELD, FILE_ITEM_SIZE_FIELD, FILE_ITEM_MD5_FIELD}
FILE_ITEM.is_extendable = false
FILE_ITEM.extensions = {}
FILE_ITEM_ARRAY_ITEMS_FIELD.name = "items"
FILE_ITEM_ARRAY_ITEMS_FIELD.full_name = ".file_item_array.items"
FILE_ITEM_ARRAY_ITEMS_FIELD.number = 1
FILE_ITEM_ARRAY_ITEMS_FIELD.index = 0
FILE_ITEM_ARRAY_ITEMS_FIELD.label = 3
FILE_ITEM_ARRAY_ITEMS_FIELD.has_default_value = false
FILE_ITEM_ARRAY_ITEMS_FIELD.default_value = {}
FILE_ITEM_ARRAY_ITEMS_FIELD.message_type = FILE_ITEM
FILE_ITEM_ARRAY_ITEMS_FIELD.type = 11
FILE_ITEM_ARRAY_ITEMS_FIELD.cpp_type = 10

FILE_ITEM_ARRAY_URL_FIELD.name = "url"
FILE_ITEM_ARRAY_URL_FIELD.full_name = ".file_item_array.url"
FILE_ITEM_ARRAY_URL_FIELD.number = 2
FILE_ITEM_ARRAY_URL_FIELD.index = 1
FILE_ITEM_ARRAY_URL_FIELD.label = 1
FILE_ITEM_ARRAY_URL_FIELD.has_default_value = false
FILE_ITEM_ARRAY_URL_FIELD.default_value = ""
FILE_ITEM_ARRAY_URL_FIELD.type = 9
FILE_ITEM_ARRAY_URL_FIELD.cpp_type = 9

FILE_ITEM_ARRAY_VERSION_FIELD.name = "version"
FILE_ITEM_ARRAY_VERSION_FIELD.full_name = ".file_item_array.version"
FILE_ITEM_ARRAY_VERSION_FIELD.number = 3
FILE_ITEM_ARRAY_VERSION_FIELD.index = 2
FILE_ITEM_ARRAY_VERSION_FIELD.label = 1
FILE_ITEM_ARRAY_VERSION_FIELD.has_default_value = false
FILE_ITEM_ARRAY_VERSION_FIELD.default_value = ""
FILE_ITEM_ARRAY_VERSION_FIELD.type = 9
FILE_ITEM_ARRAY_VERSION_FIELD.cpp_type = 9

FILE_ITEM_ARRAY.name = "file_item_array"
FILE_ITEM_ARRAY.full_name = ".file_item_array"
FILE_ITEM_ARRAY.nested_types = {}
FILE_ITEM_ARRAY.enum_types = {}
FILE_ITEM_ARRAY.fields = {FILE_ITEM_ARRAY_ITEMS_FIELD, FILE_ITEM_ARRAY_URL_FIELD, FILE_ITEM_ARRAY_VERSION_FIELD}
FILE_ITEM_ARRAY.is_extendable = false
FILE_ITEM_ARRAY.extensions = {}

file_item = protobuf.Message(FILE_ITEM)
file_item_array = protobuf.Message(FILE_ITEM_ARRAY)

